package com.flexiwork.service;

import com.flexiwork.entity.Payment;
import com.flexiwork.entity.enums.PaymentStatus;
import com.flexiwork.exception.BusinessException;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

/**
 * Renders a branded PDF for a {@link Payment}: a paid receipt or, for a pending payment, an
 * "Amount Due" invoice. Uses openhtmltopdf to convert an inline HTML/CSS template (red header band,
 * white body) into a PDF byte stream.
 */
@Service
public class PdfReceiptService {

    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("dd MMM yyyy");
    private static final DateTimeFormatter DATETIME =
            DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm").withZone(ZoneId.systemDefault());

    public byte[] render(Payment p) {
        boolean paid = p.getStatus() == PaymentStatus.PAID;
        String docType = paid ? "RECEIPT" : "INVOICE / AMOUNT DUE";
        String html = buildHtml(p, paid, docType);
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(html, null);
            builder.toStream(out);
            builder.run();
            return out.toByteArray();
        } catch (Exception e) {
            throw new BusinessException("Failed to generate PDF: " + e.getMessage());
        }
    }

    private String buildHtml(Payment p, boolean paid, String docType) {
        String ratePct = p.getCommissionRate()
                .multiply(java.math.BigDecimal.valueOf(100)).stripTrailingZeros().toPlainString();
        String paidRow = paid
                ? row("Transaction ID", esc(p.getTransactionId()))
                + row("Paid At", p.getPaidAt() != null ? DATETIME.format(p.getPaidAt()) : "-")
                : "";
        String statusColor = paid ? "#1E7E34" : "#B85C00";

        return """
            <html><head><style>
              @page { size: A4; margin: 0; }
              body { font-family: sans-serif; color: #191919; margin: 0; }
              .band { background: #EB1700; color: #fff; padding: 28px 40px; }
              .band h1 { margin: 0; font-size: 26px; letter-spacing: -0.5px; }
              .band .doc { margin-top: 6px; font-size: 13px; opacity: 0.9; letter-spacing: 1px; }
              .body { padding: 32px 40px; }
              .meta { width: 100%%; font-size: 13px; margin-bottom: 24px; }
              .meta td { padding: 4px 0; }
              .label { color: #767676; width: 40%%; }
              table.lines { width: 100%%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
              table.lines th, table.lines td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #E7E7E7; }
              table.lines th { background: #F7F7F7; color: #767676; }
              .total { font-size: 20px; font-weight: bold; color: #EB1700; }
              .status { display: inline-block; padding: 4px 12px; border-radius: 20px;
                        font-size: 12px; font-weight: bold; color: #fff; background: %s; }
              .foot { margin-top: 40px; font-size: 11px; color: #767676; }
            </style></head>
            <body>
              <div class="band">
                <h1>FlexiWork</h1>
                <div class="doc">%s &#160;&#8226;&#160; %s</div>
              </div>
              <div class="body">
                <table class="meta">
                  <tr><td class="label">Company</td><td>%s</td></tr>
                  <tr><td class="label">Job</td><td>%s</td></tr>
                  <tr><td class="label">Job Date</td><td>%s</td></tr>
                  <tr><td class="label">Status</td><td><span class="status">%s</span></td></tr>
                  %s
                </table>

                <table class="lines">
                  <tr><th>Description</th><th>Amount (LKR)</th></tr>
                  <tr><td>Total wages (%d workers attended)</td><td>%s</td></tr>
                  <tr><td>Platform commission (%s%%)</td><td>%s</td></tr>
                  <tr><td class="total">Amount %s</td><td class="total">%s</td></tr>
                </table>

                <div class="foot">
                  This document was generated by FlexiWork. Commission is charged on attended
                  workers only. Thank you for using FlexiWork.
                </div>
              </div>
            </body></html>
            """.formatted(
                statusColor,
                docType, esc(p.getReceiptNumber()),
                esc(p.getCompany().getCompanyName()),
                esc(p.getJobPost().getTitle()),
                DATE.format(p.getJobDate()),
                p.getStatus().name(),
                paidRow,
                p.getWorkersAttended(),
                p.getTotalWages().toPlainString(),
                ratePct,
                p.getCommissionAmount().toPlainString(),
                paid ? "Paid" : "Due",
                p.getCommissionAmount().toPlainString());
    }

    private String row(String label, String value) {
        return "<tr><td class=\"label\">" + esc(label) + "</td><td>" + esc(value) + "</td></tr>";
    }

    private String esc(String s) {
        if (s == null) {
            return "-";
        }
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
